### ISSUE TITLE
Pickle/cache NMF factors of scRNAseq data

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/tensor-gmm#86]
Currently the NMF is run every build. Right now it's only being run for 10 iterations which does not converge. Running it long enough to converge will take a prohibitive amount of time. The best solution to this would be to save the NMF factors so it doesn't have to be recreated from scratch.

**Comment by borcuttjahns** [comment]
Am handling this as a commit in the current PR @andrewram4287 - fix should be up soon!

**Comment by borcuttjahns** [comment]
Ok this should be handled now! Factors for rank 1-15 NNMF are saved (you can always save or add more) as well as their respective errors. Hopefully this speeds things up.
